# Generated by Django 5.1.4 on 2024-12-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_bookingtable_numberoftickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_tickets',
            field=models.PositiveIntegerField(),
        ),
    ]
